### ISSUE TITLE
Integration of Todo.txt into DoManager

### ISSUE THREAD

**Issue by viper3400** [viper3400/DoManager#19]
- DoManager should be able to interact with a todo.txt as specified at http://todotxt.com/.
- Therefore existing source code https://github.com/benrhughes/todotxt.net (under BSD licencse) may be partly used.

- [ ] #20 Simple proof of concept integration
- [ ] #21 Configurable path to todo.txt
- [ ] Useful integration of Todo.txt
